### PR TITLE
Adding the Vanilla accelerator plugins

### PR DESCRIPTION
**Pull request by SamiraAFg**
Hi, 

This is the pull request for using different versions of Vanilla Accelerator for UMA framework. 

Three versions of Vanilla accelerator are integrated into ETISS as plugins including VanillaAccelerator (float), QVanillaAccelerator (quantized) and QVanillaAcceleratorT (QVanilla + timing model)

The main changes for integrating each accelerator are:
1. adding the following files: 
    - include/etiss/IntegratedLibrary/QVanillaAcceleratorT.h
    - src/IntegratedLibrary/QVanillaAcceleratorT.cpp
2. modifying the following files to include the accelerator:
    - src/bare_etiss_processor/base.ini
    - src/IntegratedLibrary.cpp

Thanks, 
Samira

### CODE REVIEW

**Comment by wysiwyng** [comment]
I think these plugins are too specific to be included in the mainline ETISS tree. I would propose to manage the accelerator plugins in a separate repository where they don't clutter the main ETISS source. This repo can probably even be one of the MLonMCU/NNlite/etc ones.

Furthermore, I would prefer to not overwrite the default "Hello World" example by a test case for the accelerator plugins. Here I propose to adapt the example code to be buildable in a manner similar to https://github.com/tum-ei-eda/etiss_riscv_examples, and put it either in that repository, or the repository for the accelerator plugins. At the very least, it should be a separate example program in the main ETISS tree.

@DanMueGri, @PhilippvK what's your opinion on this?

**Comment by DanMueGri** [comment]
I agree, I think this should better be kept separate from ETISS. Could we make it an ETISS patch?

**Comment by mkiessling-ifx** [comment]
> I agree, I think this should better be kept separate from ETISS. Could we make it an ETISS patch?

Yes, i would be good, if there is some plug-in mechanism, for the the Accelerator plug-ins. I would also appreciate that. 
Because that increases the re-use of the core ETISS.

**Comment by PhilippvK** [comment]
Moved to https://github.com/tum-ei-eda/etiss-accelerator-plugins

**Pull request closed without merging**
