### PR TITLE
Allow bare_etiss_processor to report run-time errors to CI

### PR DESCRIPTION
**Pull request by Samanti-Das**
Bare etiss processor will now show error codes by setting a return code on exit along with the error message according to the mapping:

**Error code 0:** Proper execution, no error
**Error code 1:** Targets program error
**Error code 2:** Targets JIT engine error
**Error code 3:** Targets everything else

### CODE REVIEW

**Comment by rafzi** [comment]
thanks for this! could you please merge the current master branch into your branch? there was an error that prevented etiss from being configured correctly. we would expect that the mac tests fail here. then we would additionally need to disable the mac tests that are failing

**Comment by wysiwyng** [comment]
So as expected the Mac OS tests currently fail (which they also do on the current master, with the difference that the CI doesn't fail). But: The GCC test run on master completes with warnings, and the LLVM test run currently doesn't work because of #43. 

@rafzi should we disable the Mac OS tests or accept this PR and check whether the tests are fixable?

**Comment by rafzi** [comment]
i'd rather just disable the mac tests, because we dont really have anyone interested in the mac build right now. i'd just keep it in the build ci so that we keep the cross-platform build working

**Comment by rafzi** [comment]
great, thanks!

**Pull request merged**
