### PR TITLE
attempt to fix multiple instruction overlap

### PR DESCRIPTION
**Pull request by rafzi**
#59 

This fixes the instructionset compilation.

@wysiwyng Could you please test whether the simulation works fully?

### CODE REVIEW

**Comment by wysiwyng** [comment]
Thanks for the fix. The ARMv7M model loads now (it is not functional yet), RISC-V also looks fine. Would you mind sharing a few insights on how this fix works?

**Comment by rafzi** [comment]
The function handles collisions, as in when we have two nodes with same `opcode & mask`.

The fix addesses the missing case where the replacedNode (which is the delegate of otherNode==the colliding node) is an OverlappedNode. That case is handled by replacing the delegate of the otherNode with a new OverlappedNode that then delegates to the original replacedNode.

    otherNode  ->  replacedNode

is transformed to

    otherNode  ->  newNode   -> replacedNode

The only thing I'm unsure of, is whether the order of masks is correctly implemented. As the documentation of OverlappedNode states: `The more specific mask will match first, the[n] delegate to another node which may also be an OverlappedNode.`.

Maybe we have to do a comparison of masks here to figure out whether we should instead rewrite to

    otherNode   -> replacedNode  -> newNode

I'm also not very sure whether the first argument to the constructor of newNode is correct. Based on the current transformation is should be Instruction that has the mask of the intermediate instruction (not the most generic and not the most specific).

**Comment by wysiwyng** [comment]
I ran some tests, unfortunately while with this patch ETISS is able to load multiple overlapping `InstructionDefinition`s, overlapping instructions are not decoded properly. In the case of #59, only the first two overlapping "specialized" instructions are decoded correctly, others get decoded as the "generic" instruction.

Attached my setup to reproduce the issue, I am a bit out of ideas regarding this... [dectest.tar.gz](https://github.com/tum-ei-eda/etiss/files/7047708/dectest.tar.gz)

**Comment by wysiwyng** [comment]
I also did some tests again, seems to be fixed for now. Once someone actually gets around to implement ARMv7M we will know for sure. Merging and closing.

**Pull request merged**
