### PR TITLE
Remove segment extraction from cmake

### PR DESCRIPTION
**Pull request by fabianpedd**
This removes clutter in the binary directory when building with vector extension support.

### CODE REVIEW

**Comment by wysiwyng** [comment]
A fix like this was already merged into ETISS a while ago: https://github.com/tum-ei-eda/etiss/blob/master/examples/SW/riscv/cmake/PulpinoTarget.cmake
Your source branch is far behind the current master, please check that first.

**Comment by fabianpedd** [comment]
The ml_on_mcu however still uses the `v-ext-support` branch until I get the vector stuff working on the master branch (which I don't know how long it will take. I would really like to first test the vector instruction from my PR #76 before merging them).

**Comment by rafzi** [comment]
Since you are actively working on this feature, feel free to directly push to this branch if you need further backports.

**Comment by fabianpedd** [comment]
@rafzi thank you

**Pull request merged**
